# BDD100K 数据集配置文件

# 数据集根目录的绝对路径
# 【【【极其重要】】】请再次确认这个路径是您存放bdd100k的raw文件夹
path: /home/s604/YagoLab/Zou/pedestrian-detection-app/data/raw/bdd100k

# 训练集和验证集图片的路径 (相对于上面的'path')
train: images/train
val: images/val

# 类别信息 (BDD100K常用的10个类别)
# 确保这些类别ID和您.txt标签文件中的ID是一致的
names:
  0: pedestrian
  1: rider
  2: car
  3: truck
  4: bus
  5: train
  6: motorcycle
  7: bicycle
  8: traffic light
  9: traffic sign
