# 数据集根目录的绝对路径
# 【【【极其重要】】】请再次确认这个路径是您处理后数据的绝对路径！
path: /home/s604/YagoLab/Zou/pedestrian-detection-app/data/processed

# 训练集和验证集图片的路径 (相对于上面的'path')
train: images/train
val: images/val

# 类别信息
names:
  0: pedestrian
